### ISSUE TITLE
empty: false in delimitedvalues environment

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/pywhip#12]
```
sex:
   delimitedValues:
       delimiter: "|"
       empty: false
       allowed: [male, female]
```

will test as follows
(blank) is OK
"(blank) | male" provides error

need to be taken into account in implementation

**Comment by peterdesmet** [comment]
Updated to `empty: false` instead of `required: true`

**Comment by peterdesmet** [comment]
That is still consistent with the [new specifications](https://github.com/inbo/whip/blob/5468ffc2b4b0ab163eca4e1f5acb2470cdb95a26/docs/syntax.md) except that `empty: False` is implied by default.

**Comment by stijnvanhoey** [comment]
As empty values can not be part of delimitedvalues, the approach is as follows:

```
sex:
   delimitedValues:
       delimiter: "|"
       allowed: [male, female]
```
Does not accept empty values (as such or within the delimited values), which is equivalent to:

```
sex:
   empty: False
   delimitedValues:
       delimiter: "|"
       allowed: [male, female]
```

Whereas:
```
sex:
   empty: True
   delimitedValues:
       delimiter: "|"
       allowed: [male, female]
```
Will accept empty values OR delimited values. Empty values within delimited sequence is never accepted.
