### ISSUE TITLE
Test: if empty string => empty string

### ISSUE THREAD

**Issue by peterdesmet** [inbo/pywhip#19]
Here's some data:

``` CSV
id,foo,bar,result
1,x,y,pass
2,x,,fail
3,,y,fail
4,,pass
```

And here's a test for it:

``` YAML
bar:
  empty: true # Required to allow empty string tests
  if:
    - foo:
        allowed: x
      allowed: y
    - foo:
        allowed: ''
      allowed: ''
```

**Comment by stijnvanhoey** [comment]
Current functioning is as follows, taking into account the addition of an explicit empty: True when these values should be tested in allowed in order to make sure the condition is tested (otherwise, the condition would fail with an automated addition of `empty: False`:

```python
yaml_str = """
            bar:
              empty: true # Required to allow empty string tests
              if:
                - foo:
                    allowed: [x]
                  allowed: [y]
                - foo:
                    empty: True  # essential
                    allowed: ['']
                  allowed: ['']
            """

schema = yaml.load(yaml_str)
val = DwcaValidator(schema)
val.allow_unknown = True

document = {'foo': 'x', 'bar': 'y'}
val.validate(document) #pass

document = {'foo': 'x', 'bar': ''}
val.validate(document) #pass

document = {'foo': '', 'bar': 'y'}
val.validate(document) #fail

document = {'foo': '', 'bar': ''}
val.validate(document) #pass
```

The remaining problem is actually the second case, where the initial True on the term `bar` is not overruled by the requirement of the if-clause that only y is possible when `foo` equals x.

**Comment by stijnvanhoey** [comment]
The reason is that the first `empty: True` is tested before the other tests and when empty is actually True, the test for that term are aborted. The reason for this it to easily handle empty values in combination with other tests, where this behavior is actually wanted:

```
number:
  min: 2
  empty: True
  type: integer
```
When the number is an empty string (which is allowed for this term), the other  tests do not have any meaning anymore.
