### ISSUE TITLE
Add stringformat: url, stringformat: json

### ISSUE THREAD

**Issue by peterdesmet** [inbo/pywhip#25]
Since we plan to deprecate type (#24), `type: url` and `type: json` will get their own specification:

```yaml
website:
    stringformat: url       # Will accept "http://github.com/inbo/whip", 
                            # including urls with http, querystrings and 
                            # anchors, but not "github.com/inbo/whip"

measurements:
    stringformat: json      # Will accept {"length": 2.0} and 
                            # {"length": 2.0, "length_unit": "cm"}, but not 
                            # {'length': 2.0} or {length: 2.0} (use double 
                            # quotes) or "length": 2.0 (use curly brackets).
```
