### ISSUE TITLE
Convert `if` rule to native cerberus ruleset

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/pywhip#38]
The `if` ruleset as currently provided works has been implemented as a new rule on top of cerberus. Still, the implementation is rather *hacky* and to provide the condition `if field1 is empty than field2 must be empty` is cumbersome and not working.

An alternative is to use the currently available `dependencies` validation rule.  As such, a current schema in whip defined:
```
verbatimCoordinates:
  empty: true
  if:
    - verbatimCoordinateSystem:
        allowed: UTM 1km
      regex: '31U[D-G][S-T]\d\d\d\d' # UTM 1km for Flanders, e.g. 31UDS8748
    - verbatimCoordinateSystem:
        allowed: UTM 5km
      regex: '31U[D-G][S-T]\d\d[A-D]' # UTM 5km for Flanders, e.g. 31UDS76C
    - verbatimCoordinateSystem:
        allowed: [Belgian Lambert 72, '']
      allowed: ''
verbatimCoordinateSystem:
  empty: true
  allowed: [UTM 1km, UTM 5km, Belgian Lambert 72]      
```

would look as following in native cerberus validation rules:

```
schema = {'verbatimCoordinateSystem': {'allowed': ['UTM 1km', 'UTM 5km', 'Belgian Lambert 72'],
                                       'empty': True}, 
          'verbatimCoordinates': {
              'anyof' : [{'dependencies': {'verbatimCoordinateSystem' : 'UTM 1km'},
                          'regex': '31U[D-G][S-T]\d\d\d\d'},
                         {'dependencies': {'verbatimCoordinateSystem' : 'UTM 5km'},
                          'regex': '31U[D-G][S-T]\d\d[A-D]'},
                         {'dependencies': {'verbatimCoordinateSystem' : ['Belgian Lambert 72', '']},
                          'allowed': ['']}],
              'empty' : True
          }}
```

The main disadvantage is that we would loose the ability of using nested if-rules other than `allowed`. So for example:

```
verbatimCoordinates:
  empty: true
  if:
    - verbatimCoordinateSystem:
        regex: 'UTM [0-9]km'
      regex: '31U[D-G][S-T]\d\d\d\d' # UTM 1km for Flanders, e.g. 31UDS8748
verbatimCoordinateSystem:
  empty: true
  allowed: [UTM 1km, UTM 5km, Belgian Lambert 72]      
```
would not be able to be converted... 

I need to furhter check this out and check with cerberus-implementation plans.
