### ISSUE TITLE
Provide additional SchemaError tests

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/pywhip#42]
As some combinations of test need specific focus, some preliminar Schema-checks should be done:

- combination of `empty: True` inside an `ìf` function without a field-wide `empty: True`:

```
lifestage:
    empty: True  # as the empty rule has priority, this is required to enable empty values inside the if-loop
    if:
        sex:
            allowed: [male]
        allowed: [adult]
        empty: True
```
(the concept of `if` which further differentiate the conditions for empty values to occur)

- the presence of `empty: True` inside a `delimitedvalues` specification

```
list_of_names:
  empty: true               # The whole field can be empty...
  delimitedvalues:
    delimiter: ' | ' 
    empty: true               # NOT POSSIBLE, should raise SchemaError
```
