### ISSUE TITLE
`if` condition handling when term is not in data set

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/pywhip#44]
Consider the following specification:

```
coordinateUncertaintyInMeters:
  empty: true
  if:
    verbatimCoordinateSystem:
        allowed: UTM 1km
    numberformat: x
    allowed: '707'
```

If `verbatimCoordinateSystem` is not existing as a column, this should raise an error. This should raise a Schema/SpecificationError, as each field we describe in the Schema is considered to be required in the data set.
