### ISSUE TITLE
Format for JSON report

### ISSUE THREAD

**Issue by peterdesmet** [inbo/pywhip#48]
```yaml
executed_at: date
errors: []
results:
    total_rows: 10
    passed_rows: 6
    failed_rows: 4
    passed_row_ids: []
    warnings: []
    unspecified_fields:
        a
        b
        c
    unknown_fields:
        x
        y
        z
    specified_fields:
        field:
            specification:
                constraint: ...
                passed_rows: 0
                failed_rows: 10
                sample [limited to 10 sorted by failed_rows desc]: {
                    "value": {first_row, message, failed_rows }
                }
        type:
            allowed:
                constraint: "[Event, Sound]"
                passed_rows: 6
                failed_rows: 4
                sample: {
                    "event":
                        first_row_id: 1
                        message: "unallowed value event",
                        failed_rows: 2
                    "blabla":
                        ...
                }
            allowed_if_1:
                constraint: "Event"
                passed_rows: 6
                failed_rows: 4
                sample: {
                    "event":
                        first_row_id: 1
                        message: "unallowed value event",
                        failed_rows: 2
                    "blabla":
                        ...
                }
            minlength_if_1: 
            allowed_if_2: 
            allowed_if_3: 
            maxlength_delimitedvalue:

```
